apiVersion: 1

datasources:
  - name: InfluxDB_Telegraf
    type: influxdb
    access: proxy
    url: http://192.168.122.12:8086
    jsonData:
      version: Flux
      organization: [ORGANIZATION]
      defaultBucket: telegraf
      tlsSkipVerify: true
      httpHeaderName1: 'Authorization'
    secureJsonData:
      httpHeaderValue1: 'token [TOKEN]'
      token: '[TOKEN]'

